name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  pulumi:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Dprint check
        if: github.event_name == 'pull_request'
        run: nix develop -c dprint check

      - name: Lint
        if: github.event_name == 'pull_request'
        run: nix develop -c make lint

      - name: Pulumi login
        uses: pulumi/auth-actions@v1
        with:
          organization: UnstoppableMango
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:UnstoppableMango

      - name: Set Pulumi flags
        run: |
          flags=""
          if [ "${{ github.actor }}" = "renovate[bot]" ]; then
            flags="$flags --expect-no-changes"
          fi
          echo "PULUMI_FLAGS=$flags" >> "$GITHUB_ENV"

      - name: Preview
        if: github.event_name == 'pull_request'
        run: nix develop -c make preview

      - name: Deploy
        if: github.event_name == 'push'
        env:
          PULUMI_FLAGS: --yes ${{ env.PULUMI_FLAGS }}
        run: nix develop -c make up
